baseURL: "https://kreatofagos.gr/"
title: Kreatofagos
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
defaultContentLanguage: el

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    el:
        languageName: "Ελληνικά"
        weight: 1
        menu:
            main:
                - name: Αρχείο
                  url: archives
                  weight: 5
                - name: Αναζήτηση
                  url: search/
                  weight: 10
                - name: Ετικέτες
                  url: tags/
                  weight: 10

    en:
        languageName: "English"
        weight: 2
        title: Kreatofagos
        profileMode:
            enabled: true
            title: Kreatofagos (the Carnivore)
            # imageUrl: "#"
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
            subtitle: "Welcome to kreatofagos.gr, a greek website about the carnivore diet."
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags
        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Tags
                  url: tags
                  weight: 10
                - name: Categories
                  url: categories
                  weight: 10
                - name: Series
                  url: series
                  weight: 10
                # - name: NullLink
                #   url: "#"
                # - name: NullLink2
                #   url: "#"
                # - name: NullLink3
                #   url: "#"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Καλώς ορίσατε στο kreatofagos.gr"
    author: Me
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: Kreatofagos
        # imageUrl: "#"
        # imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Καλώς ορίσατε στο kreatofagos.gr \U0001F44B"
        Content: >
            Welcome to demo of hugo's theme PaperMod.

            - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

    socialIcons:
        - name: twitter
          url: "#"
        - name: stackoverflow
          url: "#"
        - name: codepen
          url: "#"
        - name: linkedin
          url: "#"
        - name: github
          url: "https://github.com/kreatofagos/kreatofagos.gr"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
